### ISSUE TITLE
create recreation PR to ember-vite-app for .ts component class importing importSync from @embroider/macros

### ISSUE THREAD

**Issue by mansona** [mansona/ember-vite-app#3]
create a PR as reproduction on https://github.com/mansona/ember-vite-app using ember-cli-typescript

Backing class for a simple component needs to be a .ts file and it needs to use `@embroider/macros` importSync for something. 

My thoughts are that the implementation of `importSync` is implemented in babel i.e. that the source is updated to remove the "fake call" to importSync. 

remember that that the success criteria is not **fixing** this issue, but instead creating a reproduction PR that fails with this issue 👍 

I seem to remember that the error we faced was something like "@embroider/macros does not have a named export called importSync" which is odd since we expected that code to be stripped 🤔

**Comment by lolmaus** [comment]
Done: https://github.com/mansona/ember-vite-app/pull/4

**Comment by mansona** [comment]
perfect thanks! I'll create a new entry in our board for actually fixing it, but it's probably blocked on our other Vite work 🤔
